routes/web.php
<?php

use App\Http\Controllers\AdvertNotificationController;
use App\Http\Controllers\AdvNotificationsTranslationController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\CenterEmployeeController;
use App\Http\Controllers\CenterManagerController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CenterAppointmentsController;
use App\Http\Controllers\HeaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DelegateController;
use App\Http\Controllers\DistirbuationRegionsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\PharmacistsController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SecretariatController;
use App\Http\Controllers\DeliveryTimeController;
use App\Http\Controllers\UserCartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PushNotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryTranslationsController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CoinController;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use App\Http\Controllers\SortController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\couponSettingController;
use App\Http\Controllers\DeliverRegionController;
use App\Http\Controllers\HelpTranslationController;
use App\Http\Controllers\InboxTranslationController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ProductTranslationController;
use App\Models\AdvertNotificationTranslation;
use App\Http\Controllers\UserManagmentController;
use App\Http\Controllers\RuleController;
use App\Http\Controllers\DownloadController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[HomeController::class,'studentHome']);
Route::get('/appointment/home',[AppointmentController::class ,'view'])->name('appointment');
Route::post('/appointment',[AppointmentController::class ,'search'])->name('appointment');
Route::get('/appointment/{tt?}/{center?}',[AppointmentController::class ,'search'])->name('appointment');
Route::post('/appointment-get',[AppointmentController::class ,'getAppointment'])->name('appointment-get');
Route::get('/view-centers',[AppointmentController::class ,'viewCenters'])->name('view-centers');
Route::get('/file-download', [DownloadController::class, 'index'])->name('file.download.index');
Route::get('/app-download', [DownloadController::class, 'indexapp'])->name('app.download.indexapp');



Route::get('/login', function () {
    return view('login');
})->name('login_form');
Route::post("login","App\Http\Controllers\UserController@login")->name("login");
Route::post("logout","App\Http\Controllers\UserController@logout")->name("logout");

Route::get('/home', [HomeController::class, 'index'])->name("home");
Route::get('/profile', [UserController::class, 'showProfile'])->middleware('auth')->name("profile");
Route::post('/profile', [UserController::class, 'updateProfile'])->middleware('auth')->name("profile.update");
Route::group(['middleware' => ['auth']], function() {
Route::resource('center_types', CategoryController::class);
Route::resource('centers', CenterController::class);
Route::resource('center-managers', CenterManagerController::class);
Route::resource('emps', EmployeeController::class);
Route::resource('hea', HeaController::class);

Route::get('center/emps/{id}',[CenterEmployeeController::class ,'index']);
Route::get('center/emps/{id}/{item_id}/edit',[CenterEmployeeController::class ,'edit']);
Route::delete('center/emps/{id}/{item_id}',[CenterEmployeeController::class ,'destroy']);
Route::post('center/emps/{id}',[CenterEmployeeController::class ,'store']);

Route::resource('appointments', CenterAppointmentsController::class);


Route::resource('usersRequests', UserController::class);


//Route::resource('distribuation-region', DistirbuationRegionsController::class);
//Route::get('pharmacists-requests',[ PharmacistsController::class,'pharmasticsRequests'])->name('pharmacists-requests.index');

Route::get('user-carts-requests',[ UserCartController::class,'viewRequests'])->name('user-carts-requests.index');
Route::get('filter-carts-requests/{status}',[ UserCartController::class,'filterRequests'])->name('user-carts-requests.filter');
Route::post('user-carts-request-view/{id}',[ UserCartController::class,'markOrderViewed'])->name('user-carts-requests.viewed');
Route::get('user-carts-request-details/{id}/{region?}',[ UserCartController::class,'getOrderDetails'])->name('order.details');
Route::delete('user-carts-request-details/{id}',[ UserCartController::class,'deleteOrder'])->name('order.delete');
Route::post('user-request-delegate',[ UserCartController::class,'setOrderDelegate'])->name('user-request-delegate');

Route::get('update/order',[UserCartController::class,'updateOrder'])->name('order.update');
Route::post('update/order/{id}',[UserCartController::class,'updateOrder']);

//Route::get('region/delegates/{id}',[ DistirbuationRegionsController::class,'getRegionDelegates'])->name('region.getRegionDelegates');
//Route::get('user-notifications',[ UserNotificationsController::class,'viewNotifications'])->name('user-notifications.index');
//Route::post('user-notifications',[ UserNotificationsController::class,'store'])->name('user-notifications.store');

//
Route::group(['prefix' => 'crud/{table}','middleware'=>['admin']], function($table) {
    Route::get('get', [UserController::class, 'index'])->name('crud.index');
    Route::get('get/{id}/edit', [UserController::class, 'edit'])->name('crud.edit');
    Route::get('add', [UserController::class, 'showForm'])->name('crud.add');
    Route::post('add', [UserController::class, 'store'])->name('crud.store');
    Route::post('get/{id}/update', [UserController::class, 'update'])->name('crud.edit');
    Route::delete('get/{id}/delete', [UserController::class, 'destroy'])->name('crud.destroy');
//
//
}) ;// end crud;

Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs');
Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs1');

//Route::get('categories/subs/index/', [CategoryController::class, 'sub_index'])->name('sub_index');

//get sub cat view
Route::get('categories/subs/index/{id}',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");
//Route::get('categories/subs/index/',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");

/// end sub
Route::group(['prefix' => 'sort/{table}'], function($table) {
    Route::get('get', [SortController::class, 'index'])->name('sort.index');
    Route::post('save', [SortController::class, 'store'])->name('sort.store');

}) ;// end get table data select 2;
//ales
//Route::post('store-city',[CountryController::class, 'storeCity']);
//Route::post('countries/cities',[CountryController::class, 'getCities'])->name('cities');
//Route::get('countries/cities/{country_id}',[CountryController::class, 'getCities']);
Route::post('countries/regions/', [CountryController::class, 'getSubs'])->name('countries.regions');
Route::get('countries/regions/{id}', [CountryController::class, 'getSubs']);

    Route::resource('roles', RuleController::class);
    Route::resource('users', UserManagmentController::class);

Route::get('filter/products/{cat_id}',[ProductController::class, 'filter'])->name('products');
Route::get('products_degrease', [ProductController::class, 'degreaseProducts'])->name('degrease.products');
Route::get('filter/degrease_products/{cat_id}',[ProductController::class, 'filterDegreaseProducts'])->name('degrease.products.filter');
Route::get('report/{date}', [ProductController::class, 'report'])->name('report');

//product and category soft delete
Route::get('delete/cat',[CategoryController::class,'deleteCat'])->name('categories.delete');
Route::post('delete/cat/{id}',[CategoryController::class,'deleteCat']);


Route::get('/users-accepted',[UserController::class,'users'])->name('users.accepted');
Route::get('agree/user',[UserController::class,'agree'])->name('usersRequests.agree');
Route::post('agree/user/{id}',[UserController::class,'agree']);

Route::post('send-notification', [PushNotificationController::class, 'sendNotification'])->name('notifications');


//
Route::post('projects/media/{table}', [MediaController::class, 'storeMedia'])
    ->name('projects.storeMedia');
Route::delete('projects/media/{table}', [MediaController::class, 'destroyMedia'])
    ->name('projects.deleteMedia');

Route::post('push-notification', [PushNotificationController::class, 'sendNotification'])
    ->name('app.send-notitication');

Route::get('print-document/{id}/{region?}', [PrintController::class, 'printInvoice']);

Route::post('qrcode/{var}', function ($var) {
    return QrCode::size(250)

        ->generate($var);
});
Route::get('storage-link', function(){
    return Artisan::call('storage:link');
});





//offers ales
Route::resource('offers', OfferController::class);
Route::get('filter/offers/{cat_id}',[OfferController::class, 'filter'])->name('offer.products');
//delete offer
Route::get('delete/offer',[OfferController::class,'deleteOffer'])->name('offers.delete');

app/Models/Center.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Center extends Model
{
    use HasFactory;
    protected $guarded = [];
    public  function type(){
        return $this->belongsTo("App\Models\CenterType","center_type_id","id");
    }
    public  function manager(){
        return $this->belongsTo("App\Models\User","manager_id","id");
    }
}

app/Models/CenterType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CenterType extends Model
{
    use HasFactory;

    protected $guarded = [];

    public  function centers(){
        return $this->hasMany("App\Models\Center","center_type_id","id");
    }
}

app/Http/Controllers/CenterController.php
<?php

namespace App\Http\Controllers;


use App\Models\Center;
use App\Models\CenterType;
use App\Models\Product;
use App\Models\User;
use Illuminate\Http\Request;

use App\Models\Category;

use Validator;
use DataTables;
use App\Http\Traits\allTrait;


class CenterController extends Controller
{ use allTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:category-list|category-create|category-edit|category-delete', ['only' => ['index','show']]);
        $this->middleware('permission:category-create', ['only' => ['create','store']]);
        $this->middleware('permission:category-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:category-delete', ['only' => ['destroy']]);
        $this->middleware('permission:cat_sub-list|cat_sub-create|cat_sub-edit|cat_sub-delete', ['only' => ['index','show']]);
        $this->middleware('permission:cat_sub-create', ['only' => ['create','store']]);
        $this->middleware('permission:cat_sub-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:cat_sub-delete', ['only' => ['destroy']]);
    }
    public function index( Request $request)
    {
        //
        $user = auth()->user();
        if ($request->ajax()) {
            $data = Center::with('type')->with('manager')->orderBy('id','desc')->select('*');
            return Datatables::of($data)

                ->addIndexColumn()

                ->addColumn('action', function($row) use ($user){
                    $btn = '';
                    if ($user->can('category-edit')){
                        $btn = '<button href="javascript:void(0)" data-toggle="tooltip" class="edit btn btn-primary btn-sm"  data-id="' . $row->id . '"> <i class="fa fa-edit"></i> </button> &nbsp; ';
                    }
                    if($user->can('category-delete')) {
                        $btn .= '<button href="javascript:void(0)" data-toggle="tooltip" class="delete btn btn-danger btn-sm" data-id="' . $row->id . '"> <i class="fa fa-trash-o"></i> </button > &nbsp; ';
                    }
                    $btn .= '<a href="'.url('center/emps', $row->id).'" data-toggle="tooltip" class="info btn btn-secondary btn-sm "  data-id="'.$row->id.'" style="color: white !important;"> <i class="fa fa-empire"></i>  الموظفين  </a> &nbsp; ';


                    return $btn;

                })

                ->rawColumns(['action','icon'])

                ->make(true);
        }
        $cats = CenterType::get();
        $managers = User::where('role',3)->get();
        return view('admin.centers', compact('cats','managers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $validateErrors = Validator::make($request->all(),
            [
                'name' => 'required|string|min:3',
                'address' => 'required|string|min:3',
                'center_type_id' => 'required|numeric',

            ]);
        if ($validateErrors->fails()) {
            return response()->json(['status' => 201, 'message' => $validateErrors->errors()->first()]);
        } // end if fails .
//        }
        $data =[
            'name' => $request->name,
            'address' => $request->address,
            'center_type_id' => $request->center_type_id,
            'manager_id' => $request->manager_id,
            'workers' => $request->workers,
            'lat' => $request->lat,
            'lng' => $request->lng,

        ];





        $id =  Center::updateOrCreate(['id' => $request->_id],
            $data)->id;
            $user = User::where('id',$request->manager_id)->first();
            $user->update([['center_id'=>$id],['role'=>5]]);


        return response()->json(['status'=>200,'message' => ' تم حفظ البيانات  بنجاح .' , "data"=>"" ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $item = Center::find($id);

        return response()->json($item);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return  $this->editController($id,Center::class);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validateErrors = Validator::make($request->all(),
            [
                'name' => 'required|string|min:3',
                'address' => 'required|string|min:3',
                'center_type_id' => 'required|numeric',


            ]);
        if ($validateErrors->fails()) {
            return response()->json(['status' => 201, 'message' => $validateErrors->errors()->first()]);
        } // end if fails .

        $data =[
            'name' => $request->name,
            'address' => $request->address,
            'center_type_id' => $request->center_type_id,
            'manager_id' => $request->manager_id,
            'workers' => $request->workers,

        ];

        Center::updateOrCreate(['id' => $request->_id],
            $data);
            if(!empty($request->manager_id)){
                User::where('id',$request->manager_id)->update([['center_id',$request->_id],['role'=>5]]);
            }


        return response()->json(['status'=>200,'message' => ' تم حفظ البيانات بنجاح    .' ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->destroyController($id,Center::class);

    }

//    public function getSubs($id){
//        //
//        $data = Category::where([['parent_id','=',$id],['deleted','=',0]])->orderBy('order_id')->get();
//
//        $sub = Category::find($id);
//
//        return view('admin.category_sub',compact(["data","sub"]));
//    }


}

resources/views/admin/centers/appointments.blade.php
@extends("admin_layout")
@section('content')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" ></script>
    <section id="input-style">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-content">
                        <div class="card-body">
                            <p>
                                 المواعيد


                            </p>
                            <div class="row">
                                <form action="#" method="post" id="editFromData" class="row">
                                    @csrf
                                    <input type="hidden" name="_id" id="_id">
                                <div class="col-md-3">
                                    <label for="">الاسم  </label>
                                    <input type="text" class="form-control" name="name" id="name_edit">
                                </div>
                                <div class="col-md-3">
                                    <label for="">اسم الأم  </label>
                                    <input type="text" class="form-control" name="mother_name" id="mother_name_edit" >
                                </div>
                                <div class="col-md-3">
                                    <label for="">الكنية    </label>
                                    <input type="text" class="form-control" name="last_name" id="last_name_edit">
                                </div>

                                <div class="col-md-3">
                                    <label for="">الرقم الوطني    </label>
                                    <input type="number" class="form-control" id="national_id_edit" name="national_id">
                                </div>
                                <div class="col-md-3">
                                    <label for=""> الموبايل      </label>
                                    <input type="number" class="form-control" id="mobile_edit" name="mobile">
                                </div>

                                <div class="col-md-3">
                                    <label for="">التاريخ      </label>
                                    <input type="date" name="date" class="form-control" value="<?php echo date('Y-m-d'); ?>">
                                </div>
                                <div class="col-md-3">
                                    <br>
                                    <label for="">الوقت</label>
                                    <select name="hour" id="hour">
                                        @for ($i=8;$i<=16;$i++)
                                            <option value='{{$i}}'>{{$i}}</option>
                                        @endfor
                                    </select>
                                    <select name="minute" id="minute">
                                        @for ($i=0;$i<=60;$i+=10)
                                            <option value='{{$i}}'>{{$i}}</option>
                                        @endfor
                                    </select>
                                </div>
                                </form>
                            </div>
                            @can('category-create')
                                <div class="row" style="margin: 20px;">
                                    <button type="button" id="addClick" class="btn btn-primary">إضافة</button>

                                </div>
                            @endcan
                            <br>
                            <div class="row">

                                <div class="col-sm-12" style="overflow-x:auto;">
                                    <table class="table table-striped table-sm data-table">

                                        <thead>

                                        <tr>

                                            <th>#</th>

                                            <th> الاسم</th>
                                            <th>اسم الأم    </th>
                                            <th>الكنية    </th>
                                            <th> الرقم الوطني  </th>
                                            <th>  رقم الموبايل    </th>
                                            <th> التاريخ    </th>
                                            <th> الوقت    </th>
                                                 <th >العمليات</th>

                                        </tr>

                                        </thead>

                                        <tbody>

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@push('myjs')


        <script type="text/javascript">

            $(function () {


            var table = $('.data-table').DataTable({

            destroy: true,
            processing: true,

            serverSide: true,
            stateSave: true,

            ajax: "{{ route('appointments.index') }}",

            columns: [

        {data: 'DT_RowIndex', name: 'id'},

        {data: 'student.name', name: 'student.name'},
        {data: 'student.last_name', name: 'student.last_name'},
        {data: 'student.mother_name', name: 'student.mother_name'},
        {data: 'student.national_id', name: 'student.national_id'},
        {data: 'student.mobile', name: 'student.mobile'},
        {data: 'date', name: 'date'},
        {data: 'time', name: 'time'},


        {data: 'action', name: 'action', orderable: false, searchable: false},

            ]

        });




            $('body').on('click', '.edit', function () {

            var product_id = $(this).data('id');
            $("#title").html("تعديل مدير المركز");

            $.get("{{ route('appointments.index') }}" + '/' + product_id + '/edit', function (data) {




            $("#saveBtn").val("حفظ");

            $('#_id').val(data.id);
            $('#name_edit').val(data.student.name);
            $('#last_name_edit').val(data.student.last_name);
            $('#mother_name_edit').val(data.student.mother_name);
            $('#national_id_edit').val(data.student.national_id);
            $('#mobile_edit').val(data.student.mobile);
            $('#date_edit').val(data.date);
            $('#time_edit').val(data.time);


            $("#inlineForm").modal('show');
        })


        }) ;// end edit function;

            $("#addClick").click(function (e) {
            e.preventDefault();

            $("#addClick").html('جاري الخفظ ..');
            $("#addClick").attr('disabled',true);
            var product_id = $("#_id").val();
            var url = "{{ route('appointments.store') }}";
                var name  = $("#name_edit").val();
                if(name.length < 3){
                    showErrorFunctionCustom("يرجى ادخال الاسم");
                    return;
                }
                    var mother  = $("#mother_name_edit").val();
                if(mother.length < 3){
                    showErrorFunctionCustom("يرجى ادخال اسم الام");
                    return;
                }
                var last  = $("#last_name_edit").val();
                if(last.length < 3){
                    showErrorFunctionCustom("يرجى ادخال الكنية  ");
                    return;
                }

            $.ajax({

            data: $('#editFromData').serialize(),

            url: url,

            type: "POST",

            dataType: 'json',
            timeout:40000,
            success: function (data) {
            $("#addClick").html(' حفظ');
            $("#addClick").attr('disabled',false);

            $('#editFromData').trigger("reset");

            showSuccesFunction();

            $("#inlineForm").modal('hide');

            table.draw(false);



        },

            error: function (data) {
            $("#addClick").html(' حفظ');
            $("#addClick").attr('disabled',false);

            showErrorFunction();

        }

        });
        }); // end save  record data



            $('body').on('click', '.delete', function () {
            var product_id = $(this).data("id");

            sweetConfirm( function (confirmed) {
            if (confirmed) {
            $.ajax({

            type: "DELETE",

            url: "{{ route('appointments.index') }}"+ '/' + product_id,
            data:{
            '_token':'{{csrf_token()}}'
        },
            success: function (data) {
            showSuccesFunction();
            table.draw(false);

        },

            error: function (data) { }

        });   }

        });

        }); // end delete row


        });

    </script>
@endpush