routes/web.php
<?php

use App\Http\Controllers\AdvertNotificationController;
use App\Http\Controllers\AdvNotificationsTranslationController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\CenterEmployeeController;
use App\Http\Controllers\CenterManagerController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CenterAppointmentsController;
use App\Http\Controllers\HeaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DelegateController;
use App\Http\Controllers\DistirbuationRegionsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\PharmacistsController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SecretariatController;
use App\Http\Controllers\DeliveryTimeController;
use App\Http\Controllers\UserCartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PushNotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryTranslationsController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CoinController;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use App\Http\Controllers\SortController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\couponSettingController;
use App\Http\Controllers\DeliverRegionController;
use App\Http\Controllers\HelpTranslationController;
use App\Http\Controllers\InboxTranslationController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ProductTranslationController;
use App\Models\AdvertNotificationTranslation;
use App\Http\Controllers\UserManagmentController;
use App\Http\Controllers\RuleController;
use App\Http\Controllers\DownloadController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[HomeController::class,'studentHome']);
Route::get('/appointment/home',[AppointmentController::class ,'view'])->name('appointment');
Route::post('/appointment',[AppointmentController::class ,'search'])->name('appointment');
Route::get('/appointment/{tt?}/{center?}',[AppointmentController::class ,'search'])->name('appointment');
Route::post('/appointment-get',[AppointmentController::class ,'getAppointment'])->name('appointment-get');
Route::get('/view-centers',[AppointmentController::class ,'viewCenters'])->name('view-centers');
Route::get('/file-download', [DownloadController::class, 'index'])->name('file.download.index');
Route::get('/app-download', [DownloadController::class, 'indexapp'])->name('app.download.indexapp');



Route::get('/login', function () {
    return view('login');
})->name('login_form');
Route::post("login","App\Http\Controllers\UserController@login")->name("login");
Route::post("logout","App\Http\Controllers\UserController@logout")->name("logout");

Route::get('/home', [HomeController::class, 'index'])->name("home");
Route::get('/profile', [UserController::class, 'showProfile'])->middleware('auth')->name("profile");
Route::post('/profile', [UserController::class, 'updateProfile'])->middleware('auth')->name("profile.update");
Route::group(['middleware' => ['auth']], function() {
Route::resource('center_types', CategoryController::class);
Route::resource('centers', CenterController::class);
Route::resource('center-managers', CenterManagerController::class);
Route::resource('emps', EmployeeController::class);
Route::resource('hea', HeaController::class);

Route::get('center/emps/{id}',[CenterEmployeeController::class ,'index']);
Route::get('center/emps/{id}/{item_id}/edit',[CenterEmployeeController::class ,'edit']);
Route::delete('center/emps/{id}/{item_id}',[CenterEmployeeController::class ,'destroy']);
Route::post('center/emps/{id}',[CenterEmployeeController::class ,'store']);

Route::resource('appointments', CenterAppointmentsController::class);


Route::resource('usersRequests', UserController::class);


//Route::resource('distribuation-region', DistirbuationRegionsController::class);
//Route::get('pharmacists-requests',[ PharmacistsController::class,'pharmasticsRequests'])->name('pharmacists-requests.index');

Route::get('user-carts-requests',[ UserCartController::class,'viewRequests'])->name('user-carts-requests.index');
Route::get('filter-carts-requests/{status}',[ UserCartController::class,'filterRequests'])->name('user-carts-requests.filter');
Route::post('user-carts-request-view/{id}',[ UserCartController::class,'markOrderViewed'])->name('user-carts-requests.viewed');
Route::get('user-carts-request-details/{id}/{region?}',[ UserCartController::class,'getOrderDetails'])->name('order.details');
Route::delete('user-carts-request-details/{id}',[ UserCartController::class,'deleteOrder'])->name('order.delete');
Route::post('user-request-delegate',[ UserCartController::class,'setOrderDelegate'])->name('user-request-delegate');

Route::get('update/order',[UserCartController::class,'updateOrder'])->name('order.update');
Route::post('update/order/{id}',[UserCartController::class,'updateOrder']);

//Route::get('region/delegates/{id}',[ DistirbuationRegionsController::class,'getRegionDelegates'])->name('region.getRegionDelegates');
//Route::get('user-notifications',[ UserNotificationsController::class,'viewNotifications'])->name('user-notifications.index');
//Route::post('user-notifications',[ UserNotificationsController::class,'store'])->name('user-notifications.store');

//
Route::group(['prefix' => 'crud/{table}','middleware'=>['admin']], function($table) {
    Route::get('get', [UserController::class, 'index'])->name('crud.index');
    Route::get('get/{id}/edit', [UserController::class, 'edit'])->name('crud.edit');
    Route::get('add', [UserController::class, 'showForm'])->name('crud.add');
    Route::post('add', [UserController::class, 'store'])->name('crud.store');
    Route::post('get/{id}/update', [UserController::class, 'update'])->name('crud.edit');
    Route::delete('get/{id}/delete', [UserController::class, 'destroy'])->name('crud.destroy');
//
//
}) ;// end crud;

Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs');
Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs1');

//Route::get('categories/subs/index/', [CategoryController::class, 'sub_index'])->name('sub_index');

//get sub cat view
Route::get('categories/subs/index/{id}',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");
//Route::get('categories/subs/index/',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");

/// end sub
Route::group(['prefix' => 'sort/{table}'], function($table) {
    Route::get('get', [SortController::class, 'index'])->name('sort.index');
    Route::post('save', [SortController::class, 'store'])->name('sort.store');

}) ;// end get table data select 2;
//ales
//Route::post('store-city',[CountryController::class, 'storeCity']);
//Route::post('countries/cities',[CountryController::class, 'getCities'])->name('cities');
//Route::get('countries/cities/{country_id}',[CountryController::class, 'getCities']);
Route::post('countries/regions/', [CountryController::class, 'getSubs'])->name('countries.regions');
Route::get('countries/regions/{id}', [CountryController::class, 'getSubs']);

    Route::resource('roles', RuleController::class);
    Route::resource('users', UserManagmentController::class);

Route::get('filter/products/{cat_id}',[ProductController::class, 'filter'])->name('products');
Route::get('products_degrease', [ProductController::class, 'degreaseProducts'])->name('degrease.products');
Route::get('filter/degrease_products/{cat_id}',[ProductController::class, 'filterDegreaseProducts'])->name('degrease.products.filter');
Route::get('report/{date}', [ProductController::class, 'report'])->name('report');

//product and category soft delete
Route::get('delete/cat',[CategoryController::class,'deleteCat'])->name('categories.delete');
Route::post('delete/cat/{id}',[CategoryController::class,'deleteCat']);


Route::get('/users-accepted',[UserController::class,'users'])->name('users.accepted');
Route::get('agree/user',[UserController::class,'agree'])->name('usersRequests.agree');
Route::post('agree/user/{id}',[UserController::class,'agree']);

Route::post('send-notification', [PushNotificationController::class, 'sendNotification'])->name('notifications');


//
Route::post('projects/media/{table}', [MediaController::class, 'storeMedia'])
    ->name('projects.storeMedia');
Route::delete('projects/media/{table}', [MediaController::class, 'destroyMedia'])
    ->name('projects.deleteMedia');

Route::post('push-notification', [PushNotificationController::class, 'sendNotification'])
    ->name('app.send-notitication');

Route::get('print-document/{id}/{region?}', [PrintController::class, 'printInvoice']);

Route::post('qrcode/{var}', function ($var) {
    return QrCode::size(250)

        ->generate($var);
});
Route::get('storage-link', function(){
    return Artisan::call('storage:link');
});





//offers ales
Route::resource('offers', OfferController::class);
Route::get('filter/offers/{cat_id}',[OfferController::class, 'filter'])->name('offer.products');
//delete offer
Route::get('delete/offer',[OfferController::class,'deleteOffer'])->name('offers.delete');

resources/views/admin/center-managers.blade.php
@extends("admin_layout")
@section('content')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" ></script>
    <section id="input-style">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-content">
                        <div class="card-body">
                            <p>
                                 مدراء المراكز
                            </p>
                            @can('category-create')
                                <div class="row" style="margin: 20px;">
                                    <button type="button" id="addClick" class="btn btn-primary">إضافة</button>

                                </div>
                            @endcan
                            <br>
                            <div class="row">

                                <div class="col-sm-12" style="overflow-x:auto;">
                                    <table class="table table-striped table-sm data-table">

                                        <thead>

                                        <tr>

                                            <th>#</th>

                                            <th>الاسم</th>
                                            <th>البريد الالكتروني  </th>
                                            <th> رقم الهاتف</th>


                                            <th >العمليات</th>

                                        </tr>

                                        </thead>

                                        <tbody>

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade text-left" id="inlineForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel33" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <label class="modal-title text-text-bold-600" id="title">title  </label>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>

                    </button>
                </div>
                <form action="#" method="post" id="editFromData">
                    @csrf
                    <input type="hidden" name="_id" id="_id">
                    <div class="modal-body">
                        <div class="row">


                            <div class="col-md-6"> <label> اسم  المدير </label>
                                <div class="form-group">
                                    <input type="text" name="name" id="name_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label> رقم الهاتف   </label>
                                <div class="form-group">
                                    <input type="text" name="phone" id="phone_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label>البريد الالكتروني</label>
                                <div class="form-group">
                                    <input type="text" name="email" id="email_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label>كلمة السر  </label>
                                <div class="form-group">
                                    <input type="text" name="password" id="password_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>

                        </div>


                    </div>
                    <div class="modal-footer">
                        <input type="reset" class="btn bg-light-secondary" data-dismiss="modal" value="إغلاق">
                        <input type="submit" id="saveBtn" class="btn btn-primary" value="حفظ">
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('myjs')


        <script type="text/javascript">

            $(function () {

            $("#addClick").click(function (e) {
                e.preventDefault();
                $("#saveBtn").html("إضافة");
                $("#title").html("إضافة فئة");
                $('#_id').val('') ;
                $('#editFromData').trigger("reset");
                $("#inlineForm").modal("show");


                $("#card-drag-area").html("");
            });
            var table = $('.data-table').DataTable({

            destroy: true,
            processing: true,

            serverSide: true,
            stateSave: true,

            ajax: "{{ route('center-managers.index') }}",

            columns: [

        {data: 'DT_RowIndex', name: 'id'},

        {data: 'name', name: 'name'},
        {data: 'email', name: 'email'},
        {data: 'phone', name: 'phone'},


        {data: 'action', name: 'action', orderable: false, searchable: false},

            ]

        });




            $('body').on('click', '.edit', function () {

            var product_id = $(this).data('id');
            $("#title").html("تعديل مدير المركز");

            $.get("{{ route('center-managers.index') }}" + '/' + product_id + '/edit', function (data) {




            $("#saveBtn").val("حفظ");

            $('#_id').val(data.id);
            $('#name_edit').val(data.name);
            $('#phone_edit').val(data.phone);
            $('#email_edit').val(data.email);


            $("#inlineForm").modal('show');
        })


        }) ;// end edit function;

            $("#saveBtn").click(function (e) {
            e.preventDefault();

            $("#saveBtn").html('جاري الخفظ ..');
            $("#saveBtn").attr('disabled',true);
            var product_id = $("#_id").val();
            var url = "{{ route('center-managers.store') }}";
            // if(product_id){
            //    url = "{{ route('center-managers.index') }}"+ '/' + product_id + '/update'
            // }
            $.ajax({

            data: $('#editFromData').serialize(),

            url: url,

            type: "POST",

            dataType: 'json',
            timeout:4000,
            success: function (data) {
            $("#saveBtn").html(' حفظ');
            $("#saveBtn").attr('disabled',false);

            $('#editFromData').trigger("reset");

            showSuccesFunction();

            $("#inlineForm").modal('hide');

            table.draw(false);

            // table.row.add(data.data).draw( false );

        },

            error: function (data) {
            $("#saveBtn").html(' حفظ');
            $("#saveBtn").attr('disabled',false);

            showErrorFunction();
            $("#inlineForm").modal('hide');

        }

        });
        }); // end save  record data



            $('body').on('click', '.delete', function () {
            var product_id = $(this).data("id");

            sweetConfirm( function (confirmed) {
            if (confirmed) {
            $.ajax({

            type: "DELETE",

            url: "{{ route('center-managers.index') }}"+ '/' + product_id,
            data:{
            '_token':'{{csrf_token()}}'
        },
            success: function (data) {
            showSuccesFunction();
            table.draw(false);

        },

            error: function (data) { }

        });   }

        });

        }); // end delete row


        });

    </script>
@endpush

resources/views/admin/hea.blade.php
@extends("admin_layout")
@section('content')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" ></script>
    <section id="input-style">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-content">
                        <div class="card-body">
                            <p>
                                 الهيئة الإدارية
                            </p>
                            @can('category-create')
                                <div class="row" style="margin: 20px;">
                                    <button type="button" id="addClick" class="btn btn-primary">إضافة</button>

                                </div>
                            @endcan
                            <br>
                            <div class="row">

                                <div class="col-sm-12" style="overflow-x:auto;">
                                    <table class="table table-striped table-sm data-table">

                                        <thead>

                                        <tr>

                                            <th>#</th>

                                            <th>الاسم</th>
                                            <th>البريد الالكتروني  </th>
                                            <th> رقم الهاتف</th>
                                            <th> المركز  </th>


                                            <th >العمليات</th>

                                        </tr>

                                        </thead>

                                        <tbody>

                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade text-left" id="inlineForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel33" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <label class="modal-title text-text-bold-600" id="title">title  </label>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>

                    </button>
                </div>
                <form action="#" method="post" id="editFromData">
                    @csrf
                    <input type="hidden" name="_id" id="_id">
                    <div class="modal-body">
                        <div class="row">


                            <div class="col-md-6"> <label>  الاسم    </label>
                                <div class="form-group">
                                    <input type="text" name="name" id="name_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label> رقم الهاتف   </label>
                                <div class="form-group">
                                    <input type="text" name="phone" id="phone_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label>البريد الالكتروني</label>
                                <div class="form-group">
                                    <input type="text" name="email" id="email_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label>كلمة السر  </label>
                                <div class="form-group">
                                    <input type="text" name="password" id="password_edit" placeholder="" class="form-control" required>

                                </div><br>


                            </div>
                            <div class="col-md-6"> <label> المركز    </label>
                                <div class="form-group">
                                    <select name="center_id" id="center_id_edit" class="form-control">
                                        @foreach($centers as $item)
                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>

                                </div><br>


                            </div>

                        </div>


                    </div>
                    <div class="modal-footer">
                        <input type="reset" class="btn bg-light-secondary" data-dismiss="modal" value="إغلاق">
                        <input type="submit" id="saveBtn" class="btn btn-primary" value="حفظ">
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('myjs')


        <script type="text/javascript">

            $(function () {

            $("#addClick").click(function (e) {
                e.preventDefault();
                $("#saveBtn").html("إضافة");
                $("#title").html("إضافة  ");
                $('#_id').val('') ;
                $('#editFromData').trigger("reset");
                $("#inlineForm").modal("show");


                $("#card-drag-area").html("");
            });
            var table = $('.data-table').DataTable({

            destroy: true,
            processing: true,

            serverSide: true,
            stateSave: true,

            ajax: "{{ route('hea.index') }}",

            columns: [

        {data: 'DT_RowIndex', name: 'id'},

        {data: 'name', name: 'name'},
        {data: 'email', name: 'email'},
        {data: 'phone', name: 'phone'},
        {data: 'center.name', name: 'center.name'},


        {data: 'action', name: 'action', orderable: false, searchable: false},

            ]

        });




            $('body').on('click', '.edit', function () {

            var product_id = $(this).data('id');
            $("#title").html("تعديل    ");

            $.get("{{ route('hea.index') }}" + '/' + product_id + '/edit', function (data) {




            $("#saveBtn").val("حفظ");

            $('#_id').val(data.id);
            $('#name_edit').val(data.name);
            $('#phone_edit').val(data.phone);
            $('#center_id_edit').val(data.center_id);
            $('#email_edit').val(data.email);


            $("#inlineForm").modal('show');
        })


        }) ;// end edit function;

            $("#saveBtn").click(function (e) {
            e.preventDefault();

            $("#saveBtn").html('جاري الخفظ ..');
            $("#saveBtn").attr('disabled',true);
            var product_id = $("#_id").val();
            var url = "{{ route('hea.store') }}";
             {{--if(product_id){--}}
             {{--   url = "{{ route('emps.index') }}"+ '/' + product_id + '/update'--}}
             {{--}--}}
            $.ajax({

            data: $('#editFromData').serialize(),

            url: url,

            type: "POST",

            dataType: 'json',
            timeout:4000,
            success: function (data) {
            $("#saveBtn").html(' حفظ');
            $("#saveBtn").attr('disabled',false);

            $('#editFromData').trigger("reset");

            showSuccesFunction();

            $("#inlineForm").modal('hide');

            table.draw(false);

            // table.row.add(data.data).draw( false );

        },

            error: function (data) {
            $("#saveBtn").html(' حفظ');
            $("#saveBtn").attr('disabled',false);

            showErrorFunction();
            $("#inlineForm").modal('hide');

        }

        });
        }); // end save  record data



            $('body').on('click', '.delete', function () {
            var product_id = $(this).data("id");

            sweetConfirm( function (confirmed) {
            if (confirmed) {
            $.ajax({

            type: "DELETE",

            url: "{{ route('hea.index') }}"+ '/' + product_id,
            data:{
            '_token':'{{csrf_token()}}'
        },
            success: function (data) {
            showSuccesFunction();
            table.draw(false);

        },

            error: function (data) { }

        });   }

        });

        }); // end delete row


        });

    </script>
@endpush

resources/views/admin/home.blade.php
@extends("admin_layout")
@section('content')

    <style>
       a{color: #343A40}
    </style>

    <section id="input-style">
        <div class="row">
            <div class="col-12" style="overflow-x:auto;">


                <div class="row">

                    <div class="col-xl-3 col-lg-6 col-12">
                        <a href="#">
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                        <div class="media">
                                            <div class="media-body text-left">
                                                <h3 class="mb-1 danger">{{$accepted_users ?? ''}}</h3>
                                                <span>   المواعيد المسجلة اليوم  </span>
                                            </div>
                                            <div class="media-right align-self-center">
                                                <i class="fa fa-child danger font-large-2 float-right"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                        @if(Auth::user()->role != 5)
                    <div class="col-xl-3 col-lg-6 col-12">
                        <a href="">
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                        <div class="media">
                                            <div class="media-body text-left">
                                                <h3 class="mb-1 danger">{{$today_products ?? ''}}</h3>
                                                <span>    مركز</span>
                                            </div>
                                            <div class="media-right align-self-center">
                                                <i class="fa fa-building danger font-large-2 float-right"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    @endif

                    <div class="col-xl-3 col-lg-6 col-12">
                        <a href="#">
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                        <div class="media">
                                            <div class="media-body text-left">
                                                <h3 class="mb-1 danger">{{$users ?? ''}} </h3>
                                                <span> موظف    </span>
                                            </div>
                                            <div class="media-right align-self-center">
                                                <i class="fa fa-user-circle danger font-large-2 float-right"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>



                </div>



            </div>
        </div>
    </section>


@endsection