routes/web.php
<?php

use App\Http\Controllers\AdvertNotificationController;
use App\Http\Controllers\AdvNotificationsTranslationController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\CenterEmployeeController;
use App\Http\Controllers\CenterManagerController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CenterAppointmentsController;
use App\Http\Controllers\HeaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DelegateController;
use App\Http\Controllers\DistirbuationRegionsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\PharmacistsController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SecretariatController;
use App\Http\Controllers\DeliveryTimeController;
use App\Http\Controllers\UserCartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PushNotificationController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryTranslationsController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CoinController;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use App\Http\Controllers\SortController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\HelpController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\couponSettingController;
use App\Http\Controllers\DeliverRegionController;
use App\Http\Controllers\HelpTranslationController;
use App\Http\Controllers\InboxTranslationController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ProductTranslationController;
use App\Models\AdvertNotificationTranslation;
use App\Http\Controllers\UserManagmentController;
use App\Http\Controllers\RuleController;
use App\Http\Controllers\DownloadController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[HomeController::class,'studentHome']);
Route::get('/appointment/home',[AppointmentController::class ,'view'])->name('appointment');
Route::post('/appointment',[AppointmentController::class ,'search'])->name('appointment');
Route::get('/appointment/{tt?}/{center?}',[AppointmentController::class ,'search'])->name('appointment');
Route::post('/appointment-get',[AppointmentController::class ,'getAppointment'])->name('appointment-get');
Route::get('/view-centers',[AppointmentController::class ,'viewCenters'])->name('view-centers');
Route::get('/file-download', [DownloadController::class, 'index'])->name('file.download.index');
Route::get('/app-download', [DownloadController::class, 'indexapp'])->name('app.download.indexapp');



Route::get('/login', function () {
    return view('login');
})->name('login_form');
Route::post("login","App\Http\Controllers\UserController@login")->name("login");
Route::post("logout","App\Http\Controllers\UserController@logout")->name("logout");

Route::get('/home', [HomeController::class, 'index'])->name("home");
Route::get('/profile', [UserController::class, 'showProfile'])->middleware('auth')->name("profile");
Route::post('/profile', [UserController::class, 'updateProfile'])->middleware('auth')->name("profile.update");
Route::group(['middleware' => ['auth']], function() {
Route::resource('center_types', CategoryController::class);
Route::resource('centers', CenterController::class);
Route::resource('center-managers', CenterManagerController::class);
Route::resource('emps', EmployeeController::class);
Route::resource('hea', HeaController::class);

Route::get('center/emps/{id}',[CenterEmployeeController::class ,'index']);
Route::get('center/emps/{id}/{item_id}/edit',[CenterEmployeeController::class ,'edit']);
Route::delete('center/emps/{id}/{item_id}',[CenterEmployeeController::class ,'destroy']);
Route::post('center/emps/{id}',[CenterEmployeeController::class ,'store']);

Route::resource('appointments', CenterAppointmentsController::class);


Route::resource('usersRequests', UserController::class);


//Route::resource('distribuation-region', DistirbuationRegionsController::class);
//Route::get('pharmacists-requests',[ PharmacistsController::class,'pharmasticsRequests'])->name('pharmacists-requests.index');

Route::get('user-carts-requests',[ UserCartController::class,'viewRequests'])->name('user-carts-requests.index');
Route::get('filter-carts-requests/{status}',[ UserCartController::class,'filterRequests'])->name('user-carts-requests.filter');
Route::post('user-carts-request-view/{id}',[ UserCartController::class,'markOrderViewed'])->name('user-carts-requests.viewed');
Route::get('user-carts-request-details/{id}/{region?}',[ UserCartController::class,'getOrderDetails'])->name('order.details');
Route::delete('user-carts-request-details/{id}',[ UserCartController::class,'deleteOrder'])->name('order.delete');
Route::post('user-request-delegate',[ UserCartController::class,'setOrderDelegate'])->name('user-request-delegate');

Route::get('update/order',[UserCartController::class,'updateOrder'])->name('order.update');
Route::post('update/order/{id}',[UserCartController::class,'updateOrder']);

//Route::get('region/delegates/{id}',[ DistirbuationRegionsController::class,'getRegionDelegates'])->name('region.getRegionDelegates');
//Route::get('user-notifications',[ UserNotificationsController::class,'viewNotifications'])->name('user-notifications.index');
//Route::post('user-notifications',[ UserNotificationsController::class,'store'])->name('user-notifications.store');

//
Route::group(['prefix' => 'crud/{table}','middleware'=>['admin']], function($table) {
    Route::get('get', [UserController::class, 'index'])->name('crud.index');
    Route::get('get/{id}/edit', [UserController::class, 'edit'])->name('crud.edit');
    Route::get('add', [UserController::class, 'showForm'])->name('crud.add');
    Route::post('add', [UserController::class, 'store'])->name('crud.store');
    Route::post('get/{id}/update', [UserController::class, 'update'])->name('crud.edit');
    Route::delete('get/{id}/delete', [UserController::class, 'destroy'])->name('crud.destroy');
//
//
}) ;// end crud;

Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs');
Route::get('categories/subs/{id}', [CategoryController::class, 'getSubs'])->name('category.subs1');

//Route::get('categories/subs/index/', [CategoryController::class, 'sub_index'])->name('sub_index');

//get sub cat view
Route::get('categories/subs/index/{id}',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");
//Route::get('categories/subs/index/',[CategoryController::class, 'get_sub_cat'])->name("get_sub.category");

/// end sub
Route::group(['prefix' => 'sort/{table}'], function($table) {
    Route::get('get', [SortController::class, 'index'])->name('sort.index');
    Route::post('save', [SortController::class, 'store'])->name('sort.store');

}) ;// end get table data select 2;
//ales
//Route::post('store-city',[CountryController::class, 'storeCity']);
//Route::post('countries/cities',[CountryController::class, 'getCities'])->name('cities');
//Route::get('countries/cities/{country_id}',[CountryController::class, 'getCities']);
Route::post('countries/regions/', [CountryController::class, 'getSubs'])->name('countries.regions');
Route::get('countries/regions/{id}', [CountryController::class, 'getSubs']);

    Route::resource('roles', RuleController::class);
    Route::resource('users', UserManagmentController::class);

Route::get('filter/products/{cat_id}',[ProductController::class, 'filter'])->name('products');
Route::get('products_degrease', [ProductController::class, 'degreaseProducts'])->name('degrease.products');
Route::get('filter/degrease_products/{cat_id}',[ProductController::class, 'filterDegreaseProducts'])->name('degrease.products.filter');
Route::get('report/{date}', [ProductController::class, 'report'])->name('report');

//product and category soft delete
Route::get('delete/cat',[CategoryController::class,'deleteCat'])->name('categories.delete');
Route::post('delete/cat/{id}',[CategoryController::class,'deleteCat']);


Route::get('/users-accepted',[UserController::class,'users'])->name('users.accepted');
Route::get('agree/user',[UserController::class,'agree'])->name('usersRequests.agree');
Route::post('agree/user/{id}',[UserController::class,'agree']);

Route::post('send-notification', [PushNotificationController::class, 'sendNotification'])->name('notifications');


//
Route::post('projects/media/{table}', [MediaController::class, 'storeMedia'])
    ->name('projects.storeMedia');
Route::delete('projects/media/{table}', [MediaController::class, 'destroyMedia'])
    ->name('projects.deleteMedia');

Route::post('push-notification', [PushNotificationController::class, 'sendNotification'])
    ->name('app.send-notitication');

Route::get('print-document/{id}/{region?}', [PrintController::class, 'printInvoice']);

Route::post('qrcode/{var}', function ($var) {
    return QrCode::size(250)

        ->generate($var);
});
Route::get('storage-link', function(){
    return Artisan::call('storage:link');
});





//offers ales
Route::resource('offers', OfferController::class);
Route::get('filter/offers/{cat_id}',[OfferController::class, 'filter'])->name('offer.products');
//delete offer
Route::get('delete/offer',[OfferController::class,'deleteOffer'])->name('offers.delete');

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{

    /// Register Function

    public function UserRegister(Request $request){

        $validator = Validator::make($request ->all(),[
            'name'=>'required|min:2|string',
            'password'=>'required|min:8 ',
            'phone'=>'required|unique:users',
            'address'=>'required|min:3'
        ]);

        if($validator -> fails()){
            return response()->json([
                "status"=>201,
                "message"=>$validator->errors()->first()
            ]);
        }else{
            if(!empty($request->email)){
                $check = User::where('email','=',$request->email)->get();
                if(count($check)>0){
                    return response()->json([
                        "status"=>201,
                        "message"=>"البريد المدخل مسجل مسبقا"
                    ]);
                }

            }
            $user_data = [
                'name'=>$request->name,
                'phone'=>$request->phone,
                'password'=>Hash::make($request->password),
                'address'=>$request->address,
                'block'=>$request->block,

                'role'=> 2,
                'status'=> 0,
                'region_id'=> $request->region_id,
                'lat'=>$request->lat,
                'lng'=>$request->lng,
            ];
            if(!empty($request->email)){
                $user_data['email']= $request->email;

            }
            if(!empty($request->input("image"))){
                $image= base64_decode($request->image);

                $image = str_replace('data:image/jpeg;base64,', '', $image);
                $imageName = 'pharma_'.time().'.'."png";
                Storage::disk('public')->put('/pharma/' . $imageName , $image);


                $user_data["image"] = "market/". $imageName;

            }
            if(!empty($request->input("avatar"))){
                $image= base64_decode($request->avatar);

                $image = str_replace('data:image/jpeg;base64,', '', $image);
                $imageName = 'pharma_av_'.time().'.'."png";
                Storage::disk('public')->put('/market/ava/' . $imageName , $image);


                $user_data["avatar"] = "market/". $imageName;


            }

            $data = User::create(
        $user_data
            );
            return response()->json([
                "status"=>200,
                "message"=>$data,
            ]);
        }
    }
    public function updateData(Request $request , $id){

        $validator = Validator::make($request ->all(),[
            'name'=>'required|min:2|string',
            'phone'=>'required',

            'address'=>'required|min:3'
        ]);

        if($validator -> fails()){
            return response()->json([
                "status"=>201,
                "message"=>$validator->errors()->first()
            ]);
        }else{
            if(!empty($request->old_password) && !empty($request->password) ){
                $user = User::find($id);
                if(!Hash::check($request->input('old_password'), $user->first()->password)) {
                    return response()->json([
                        "status"=>201,
                        "message"=>"كلمة السر القديمة غير صحيحة"
                    ]);
                    }
                }


            $data = [

                'name'=>$request->name,

                'phone'=>$request->phone,
                'email'=>$request->email,

                'address'=>$request->address,
                'lat'=>$request->lat,
                'lng'=>$request->lng,
                'block'=>$request->block,
                'region_id'=>$request->region_id,


            ];
            if(!empty($request->input("password"))){

                $data['password'] = Hash::make($request->password);
            }   if(!empty($request->input("email"))){
                $data['email'] = $request->email;
            }
             User::where('id','=',$id)->update(
            $data
            );


            return response()->json([
                "status"=>200,
                "data"=>User::find($id),
                "message"=>"تم التعديل بنجاح"

            ]);
        }
    }


    /// Login Function

    public function UserLogin(Request $request){
        $user = User::where("phone","=",$request->input("phone"))->orWhere('email','=',$request->input("phone"))->get();
        $validator = Validator::make($request ->all(),[
            'phone'=>'required |min:10|max:15',
            'password'=>'required|min:8',

        ]);
        if($validator->fails()){
            return response()->json([
                "status"=>201,
                "message"=>$validator->errors()->first(),
            ]);
        }else{
            if(count($user)>0){
                // if(Hash::check($request->input('password'), $user->first()->password)){
                    if($request->input('password')){
                //  if( intval( $user->first()->status)==1  ){
                       return response()->json([
                           "status"=>200,
                           "message"=>$user->first(),
                       ]);
                //    }
                //    else{
                //        return response()->json([
                //            "status"=>201,
                //            "message"=>"الرجاء التواصل مع الادارة لتفعيل الحساب",
                //        ]);
                //    }

                }else{
                    return response()->json([
                        "status"=>201,
                        "message"=>"password error",
                    ]);
                }
            }else{
                return response()->json([
                    "status"=>404,
                    "message"=>"Not Found",
                ]);
            }
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('admin_layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <h2>إضافة مستخدم جديد</h2>
            </div>
            <br>
            <br>
            <br>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> رجوع</a>
            </div>
            <br>
            <br>
            <br>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>اووه!</strong> هناك مشكلة بمدخلاتك.<br><br>

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif



    {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الاسم:</strong>
                {!! Form::text('name', null, array('placeholder' => 'الاسم','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الايميل:</strong>
                {!! Form::text('email', null, array('placeholder' => 'الايميل','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>كلمة المرور:</strong>
                {!! Form::password('password', array('placeholder' => 'كلمة المرور','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>تأكيد كلمة المرور:</strong>
                {!! Form::password('confirm-password', array('placeholder' => 'تأكيد كلمة المرور ','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الدور:</strong>
                {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">حفظ</button>
        </div>
    </div>
    {!! Form::close() !!}

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin_layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <h2>تعديل بيانات المستخدم</h2>
            </div>
            <br>
            <br>
            <br>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> رجوع</a>
            </div>
            <br>
            <br>
            <br>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>اووه!</strong> هناك مشكلة بمدخلاتك.<br><br>

            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الاسم:</strong>
                {!! Form::text('name', null, array('placeholder' => 'الاسم','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الايميل:</strong>
                {!! Form::text('email', null, array('placeholder' => 'الايميل','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>كلمة المرور:</strong>
                {!! Form::password('password', array('placeholder' => 'كلمة المرور','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>التاكيد:</strong>
                {!! Form::password('confirm-password', array('placeholder' => 'التاكيد,','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الادوار:</strong>
                {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">تعديل</button>
        </div>
    </div>
    {!! Form::close() !!}
@endsection

resources/views/admin/users/index.blade.php
@extends('admin_layout')



@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <h2>ادارة المستخدمين</h2>
            </div>
            <br>
            <br>
            <br>
            @can('user-create')
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('users.create') }}"> اضافة مستخدم</a>
            </div>
            @endcan
            <br>
            <br>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>الاسم</th>
            <th>الايميل</th>
            <th>الادوار</th>
            <th width="280px">العمليات</th>
        </tr>
        @foreach ($data as $key => $user)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    @if(!empty($user->getRoleNames()))
                        @foreach($user->getRoleNames() as $v)
                            <label class="badge badge-success">{{ $v }}</label>
                        @endforeach
                    @endif
                </td>
                <td>
                    <a class="btn btn-info" style="margin: 5px;" href="{{ route('users.show',$user->id) }}">عرض</a>

                    @can('user-edit')
                        <a class="btn btn-primary" style="margin: 5px;" href="{{ route('users.edit',$user->id) }}">تعديل</a>

                    @endcan
                    @can('user-delete')
                        {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                        {!! Form::submit('حذف', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}

                    @endcan

                </td>
            </tr>
        @endforeach
    </table>


    {!! $data->render() !!}

@endsection

resources/views/admin/users/show.blade.php
@extends('admin_layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <h2> عرض المستخدم</h2>
            </div>
            <br>
            <br>
            <br>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> رجوع</a>
            </div>
            <br>
            <br>
            <br>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الاسم:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الايميل:</strong>
                {{ $user->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>الادوار:</strong>
                @if(!empty($user->getRoleNames()))
                    @foreach($user->getRoleNames() as $v)
                        <label class="badge badge-success">{{ $v }}</label>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection